apiVersion: v1
kind: Service
metadata:
  name: involvedparties
  namespace: test-poc
spec:
  ports:
   - port: 7800
     name: restport
     protocol: TCP
     targetPort: 7800
   - port: 7600
     name: restadmin
     protocol: TCP
     targetPort: 7600
  selector:
    app: involvedparties
  type: ClusterIP
